### PR TITLE
Fixed #219 of upstream. Can now render multiple graphs at the same time.

### LINKED ISSUE #219: Unable to create two instances of react-digraph correctly
**Describe the bug**
I'd like to show two react-digraph instances on the page, so users can see two graph side-by-side. However, only the first graph shows the graph while the second instance displays empty canvas.

**To Reproduce**
1. Create two instances of react-digraph and pass the same graph to both of them.
2. You will see only the first instance displays the graph correctly, the second one is empty.

**Expected behavior**
See both graphs on the same page.

**Screenshots**
Screen Shot 2020-05-14 at 10 03 49 AM

https://codesandbox.io/s/react-digraph-di2dv?file=/src/index.js

**Desktop (please complete the following information):**
 - OS: Mac v10.15.3
 - Browser Chrome
 - Version v81.0.4044.138

### PR DESCRIPTION
**Pull request by ajbogh**
- Fixed rendering and element selection to allow for multiple graphs on the same webpage. 
- Fixed various edge rendering issues as well, particularly noticeable in the Transformer example.
- Cleaned up the examples.

This PR should require a major version change due to breaking changes in the CSS for the zoom controls.

Screenshot_2020-07-17_00-21-00

### CODE REVIEW

File: src/components/graph-view.js [hunk 1]
```diff
@@ -1360,14 +1361,20 @@ class GraphView extends React.Component<IGraphViewProps, IGraphViewState> {
...
+      edgeContainer = this.viewWrapper.current.querySelector(
+        `[id='${containerId}']`
+      );
     } else if (edgeContainer) {
-      const customContainer = document.getElementById(customContainerId);
+      const customContainer = this.viewWrapper.current.querySelector(
+        `[id='${customContainerId}']`
+      );
 
       edgeContainer.style.display = '';
```
Comment (chiayenhung) [inline src/components/graph-view.js:1380]: Do we need to change 
https://github.com/uber/react-digraph/blob/94bd6525f459615316c06c64da779b66d1c0a136/src/components/graph-view.js#L190-L191
as well?

Comment (ajbogh) [reply src/components/graph-view.js:1380]: Thanks for checking. I'll fix this.

Comment (ajbogh) [reply src/components/graph-view.js:1393]: Fixed.

File: src/components/edge.js [hunk 2]
```diff
@@ -437,7 +432,11 @@ class Edge extends React.Component<IEdgeProps> {
     // Note: document.getElementById is by far the fastest way to get a node.
     // compare 2.82ms for querySelector('#node-a2 use.node') vs
     // 0.31ms and 99us for document.getElementById()
-    const nodeElem = document.getElementById(`node-${trg[nodeKey]}`);
+    // Although it doesn't allow multiple graphs.
+    // We can use viewWrapperElem to scope the querySelector to a smaller set of elements to improve the speed
+    const nodeElem = viewWrapperElem.querySelector(
+      `[id='node-${trg[nodeKey]}']`
```
Comment (ksnyder9801) [inline src/components/edge.js:438]: if we’re doing breaking changes, should we change ids to classes so we don’t need to use these workarounds for duplicate ids within the same document?

File: src/components/graph-view.js [hunk 3]
```diff
@@ -1457,8 +1477,8 @@ class GraphView extends React.Component<IGraphViewProps, IGraphViewState> {
       return;
     }
 
-    const graphControlsWrapper = this.viewWrapper.current.ownerDocument.getElementById(
-      'react-digraph-graph-controls-wrapper'
+    const graphControlsWrapper = this.viewWrapper.current.querySelector(
+      '#react-digraph-graph-controls-wrapper'
```
Comment (ksnyder9801) [inline src/components/graph-view.js:1481]: same comment as above

File: src/components/edge.js (hunk 2 above)
Comment (ajbogh) [reply src/components/edge.js:438]: Perhaps in the next PR we can address that. Please feel free to create a new PR after this if you want.

You are right that this will be a breaking change, so we have the opportunity to make a number of improvements.
