### PR TITLE
resolve #212

### LINKED ISSUE #212: Behaviour for node with key=0
**Describe the bug**
Edge is not created for the node which has `node[NODE_KEY]=0`
Additionally, you cannot drag that node.

**To Reproduce**
Steps to reproduce the behaviour:
1. With the sample graph in the tutorial on top-level README.md
2. Add node with id=0 and connect to another node

That means for example,
```
{
    "nodes": [
        {
            "id": 0,
            "title": "Node 0",
            "x": 0,
            "y": 0,
            "type": "empty"
        },
        {
            "id": 1,
            "title": "Node A",
            "x": 258.3976135253906,
            "y": 331.9783248901367,
            "type": "empty"
        },
        {
            "id": 2,
            "title": "Node B",
            "x": 593.9393920898438,
            "y": 260.6060791015625,
            "type": "empty"
        },
        {
            "id": 3,
            "title": "Node C",
            "x": 237.5757598876953,
            "y": 61.81818389892578,
            "type": "custom"
        },
        {
            "id": 4,
            "title": "Node C",
            "x": 600.5757598876953,
            "y": 600.81818389892578,
            "type": "custom"
        }
    ],
    "edges": [
        {
            "source": 1,
            "target": 2,
            "type": "emptyEdge"
        },
        {
            "source": 2,
            "target": 4,
            "type": "emptyEdge"
        },
        {
            "source": 0,
            "target": 4,
            "type": "emptyEdge"
        }
    ]
}
```

**Expected behavior**
`Node with id=0` should be connected to `Node with id=4`
`Node with id=0` should be draggable.

**Screenshots**
Screen Shot 2020-04-26 at 5 59 02 PM

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser: Chrome
 - Version: 81.0.4044.122 (Official Build) (64-bit)

**Additional Context**
I realized there are many occurrences of expression like  `key-${id || ''}` ([getNodeById()](https://github.com/uber/react-digraph/blob/912a8f49e1a8f30e180719f04706622b7d58b10b/src/components/graph-view.js#L309)).
It seems there are similar value checks everywhere in the code, which does special behaviour when id = 0.
I think it is helpful to explicitly state that the key must not be 0 in the doc and/or throw an appropriate error message.

### PR DESCRIPTION
**Pull request by maekawataiki**
Fix #212 

Problem: Node with key=0 has weird behaviour because value check fails. (ex. `!node[nodeKey]`)
Solution: All occurrence of value check on node key, edge source, and edge target are replaced with an explicit comparison with null. (a.k.a. `node[nodeKey] == null`)

The example code is also changed to demonstrate the case using the node with key=0.

### CODE REVIEW

File: src/examples/graph.js [hunk 1]
```diff
@@ -54,7 +54,7 @@ const sample: IGraph = {
     {
       handleText: '5',
       handleTooltipText: '5',
-      source: 'start1',
+      source: 0,
```
Comment (ajbogh) [inline src/examples/graph.js:57]: You can create a test for this, but please don't modify the examples.

Comment (maekawataiki) [reply src/examples/graph.js]: Ok. Added some test cases and fixed the change.
