### PR TITLE
Fixed zoom issue with d3 v4 adding style property

### LINKED ISSUE #71: Uncaught TypeError: nodesSelection.exit(...).transition is not a function
We're getting this error on v4.1.5:
```
graph-view.js:693 Uncaught TypeError: nodesSelection.exit(...).transition is not a function
    at RadiumEnhancer.GraphView._this.renderNodes (graph-view.js:693)
    at RadiumEnhancer.GraphView._this.renderView (graph-view.js:790)
    at RadiumEnhancer.render (graph-view.js:929)
    at RadiumEnhancer.render (enhancer.js:265)
    at finishClassComponent (react-dom.development.js:13085)
    at updateClassComponent (react-dom.development.js:13047)
    at beginWork (react-dom.development.js:13715)
    at performUnitOfWork (react-dom.development.js:15741)
    at workLoop (react-dom.development.js:15780)
    at HTMLUnknownElement.callCallback (react-dom.development.js:100)
```

This does not happen on this commit of the fork: https://github.com/vicapow/react-digraph/tree/d3-as-direct-dependency-dist

### PR DESCRIPTION
**Pull request by ajbogh**
I'm not sure if this fixes #71 as I can't repro the problem, but this certainly does fix a zoom issue that I noticed with d3 v4. I have a StackOverflow question out for it as well, so hopefully we won't need to use hacks.

https://stackoverflow.com/questions/52430636/d3-js-v4-adds-transform-matrix-style-when-transform-attribute-is-modified-preve

### CODE REVIEW

File: src/components/graph-view.js [hunk 1]
```diff
@@ -904,10 +902,15 @@ class GraphView extends Component {
...
-
     // Update the view w/ new zoom/pan
-    const view = d3.select(this.view)
-      .attr("transform", this.state.viewTransform);
+    const view = d3.select(this.view);
+    const viewNode = view.node();
+    if (viewNode) {
+      const { k, x, y } = this.state.viewTransform;
+      view.attr("transform", this.state.viewTransform);
+      // viewNode.setAttribute('transform', `translate(${x},${y}) scale(${k})`);
```
Comment (ajbogh) [inline src/components/graph-view.js]: This is a note to understand what d3 does with transform. We could do the same thing with raw JS if we wanted.

File: src/components/graph-view.js [hunk 2]
```diff
@@ -904,10 +902,15 @@ class GraphView extends Component {
...
+      viewNode.style.transform = null;
```
Comment (ajbogh) [inline src/components/graph-view.js]: d3 (or something else), for whatever reason, is adding a transform style when the transform attribute is modified in any way. Whether we use pure JS to change the attribute, or if we use d3 to set the attribute something adds a transform style that overrides our transform attribute. Setting that style to null stops that from happening.

File: src/components/graph-controls.js [hunk 3]
```diff
@@ -102,15 +102,15 @@ class GraphControls extends Component {
   }
 
   // Modify current zoom of graph-view
-  zoom(e){
+  zoom = (e) => {
```
Comment (ajbogh) [inline src/components/graph-controls.js]: The changes in this file are automatic formatting due to slight changes while finding the bug. We also didn't need the bind call, so I removed that.

**Comment by johnvf** [comment]
I checked out your changes - I'm still not 100% sure of the underlying bug, but the code looks good and I tested your code locally and didn't see any regressions.

lgtm

**Comment by NameFILIP** [comment]
Cool, do you plan to publish the `4.1.6` version?
