### PR TITLE
Fix #300

### LINKED ISSUE #300: Unable to resolve dependency tree
**Describe the bug**
Running npm install after cloning the repo fails with the error message provided in the screenshots part.

**To Reproduce**
1. Clone the repo
2. Run npm install
3. See error

**Expected behavior**
I guess the install should complete successfully, so we can run `npm run serve` and use the examples afterwards.

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: OSX

**Additional context**

### PR DESCRIPTION
**Pull request by Djazouli**
Reading the error message from #300 I understand that some provided versions are too low, so I bumped them, and it worked.

### CODE REVIEW

File: src/utilities/layout-engine/horizontal-tree.js [hunk 1]
```diff
@@ -83,7 +83,9 @@ class HorizontalTree extends SnapToGrid {
 
     if (nodeLocationOverrides) {
       for (const gNodeId in nodeLocationOverrides) {
-        if (nodeLocationOverrides.hasOwnProperty(gNodeId)) {
+        if (
+          Object.prototype.hasOwnProperty.call(nodeLocationOverrides, gNodeId)
```
Comment (ajbogh) [inline src/utilities/layout-engine/horizontal-tree.js:87]: Why did this need to change?

**Review by ajbogh — COMMENTED** [review]
Thanks for the PR @Djazouli. I've left a comment in the code, can you help me understand why that line needed to change?

File: src/utilities/layout-engine/horizontal-tree.js (hunk 1 above)
Comment (Djazouli) [reply src/utilities/layout-engine/horizontal-tree.js:87]: The new version of eslint doesn't accept the usage of prototype builtins. 
(see the following rule: [https://eslint.org/docs/rules/no-prototype-builtins](https://eslint.org/docs/rules/no-prototype-builtins) )

**Review by ajbogh — APPROVED** [review]
