### PR TITLE
Fix #240 - cannot delete nodes with multiple graphs.

### LINKED ISSUE #240: onDeleteNode is not working in Firefox
**Describe the bug**
I am trying to delete a node in Firefox but it didn't trigger function onDeleteNode  or canDeleteNode 
it is working perfectly on Chrome. 

**Desktop (please complete the following information):**
 - Browser  Firefox
 - Version [78.0.2]

**Additional context**
any idea how can I solve the problem

### PR DESCRIPTION
**Pull request by ajbogh**
Peek 2020-08-05 12-35

### CODE REVIEW

File: src/components/edge.js [hunk 1]
```diff
@@ -425,7 +425,7 @@ class Edge extends React.Component<IEdgeProps> {
   ) {
     let response = Edge.getDefaultIntersectResponse();
 
-    if (trg[nodeKey] == null) {
+    if (trg == null || trg[nodeKey] == null) {
```
Comment (ajbogh) [inline src/components/edge.js:428]: Fixes a minor console error that shows up when a node is deleted and the connected edges try to calculate their positions.

File: src/components/graph-view.js [hunk 2]
```diff
@@ -400,10 +394,15 @@ class GraphView extends React.Component<IGraphViewProps, IGraphViewState> {
...
 
       // remove node
-      // The timeout avoids a race condition
-      setTimeout(() => {
-        GraphUtils.removeElementFromDom(`node-${nodeId}-container`);
-      });
+      const timeoutId = `nodes-${nodeId}`;
+
+      // cancel an asyncRenderNode animation
+      cancelAnimationFrame(this.nodeTimeouts[timeoutId]);
```
Comment (ajbogh) [inline src/components/graph-view.js:400]: This fixes the race condition bug by cancelling the asyncRenderNode method. Now nodes are deleted and stay deleted.

File: src/components/graph-view.js [hunk 3]
```diff
@@ -605,7 +612,7 @@ class GraphView extends React.Component<IGraphViewProps, IGraphViewState> {
     }
   };
 
-  handleEdgeSelected = e => {
+  handleEdgeSelected = (e: any) => {
```
Comment (ajbogh) [inline src/components/graph-view.js:615]: Minor flowtype redline fix.

File: src/index.js [hunk 4]
```diff
@@ -25,6 +25,7 @@ export type IEdgeType = IEdge;
 export { default as GraphUtils } from './utilities/graph-util';
 export { default as Node } from './components/node';
 export type INodeType = INode;
+// eslint-disable-next-line prettier/prettier
```
Comment (ajbogh) [inline src/index.js:28]: Fixes an annoying problem with prettier trying to fix the line breaks when it doesn't need to.
